menu:
  - home: 
    name: "Home"
    url: "/home"
    html_file: "home.html"
    markdown_file: "home.md.py"
  - news: 
    name: "News"
    url: "/news"
    html_file: "news.html"
    markdown_file: "news.md.py"
  - kontakt: 
    name: "Kontakt"
    url: "/contact"
    html_file: "contact.html"
    markdown_file: "contact.md.py"
  #- md_test:
  #  name: "Markdown"
  #  url: "/md_test"
  #  html_file: "md_test.html"
  #  markdown_file: "md_test.md.py"
